name: hova_ai
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.7
  intl: ^0.19.0
  floor: ^1.4.2
  retrofit: ^4.0.3
  flutter_hooks: ^0.20.4
  dio: ^5.4.0
  hovering: ^1.0.4
  flutter_native_splash: ^2.3.10
  go_router: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.6
  floor_generator: ^1.4.2
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/icon.png'
  web:
    generate: true
    image_path: 'assets/icons/icon.png'

  windows:
    generate: true
    image_path: 'assets/icons/icon.png'

  macos:
    generate: true
    image_path: 'assets/icons/icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

flutter_native_splash:
  background_image: 'assets/icons/icon.png'
  android: true
  ios: true
  web: true
